# Form implementation generated from reading ui file 'd:\0\SEMESTER 6\Pemrograman Visual (S6)\Tugas\week5.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 20, 80, 20))
        self.label_name.setObjectName("label_name")
        self.nameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(120, 20, 250, 25))
        self.nameInput.setObjectName("nameInput")
        self.label_email = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(20, 50, 80, 20))
        self.label_email.setObjectName("label_email")
        self.emailInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.emailInput.setGeometry(QtCore.QRect(120, 50, 250, 25))
        self.emailInput.setObjectName("emailInput")
        self.label_age = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(20, 80, 80, 20))
        self.label_age.setObjectName("label_age")
        self.ageInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ageInput.setGeometry(QtCore.QRect(120, 80, 250, 25))
        self.ageInput.setObjectName("ageInput")
        self.label_phone = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_phone.setGeometry(QtCore.QRect(20, 110, 120, 20))
        self.label_phone.setObjectName("label_phone")
        self.phoneInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.phoneInput.setGeometry(QtCore.QRect(120, 110, 250, 25))
        self.phoneInput.setObjectName("phoneInput")
        self.label_address = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_address.setGeometry(QtCore.QRect(20, 140, 80, 20))
        self.label_address.setObjectName("label_address")
        self.addressInput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.addressInput.setGeometry(QtCore.QRect(120, 140, 250, 60))
        self.addressInput.setObjectName("addressInput")
        self.label_gender = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_gender.setGeometry(QtCore.QRect(20, 210, 80, 20))
        self.label_gender.setObjectName("label_gender")
        self.genderDropdown = QtWidgets.QComboBox(parent=self.centralwidget)
        self.genderDropdown.setGeometry(QtCore.QRect(120, 210, 250, 25))
        self.genderDropdown.setObjectName("genderDropdown")
        self.label_education = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_education.setGeometry(QtCore.QRect(20, 240, 80, 20))
        self.label_education.setObjectName("label_education")
        self.educationDropdown = QtWidgets.QComboBox(parent=self.centralwidget)
        self.educationDropdown.setGeometry(QtCore.QRect(120, 240, 250, 25))
        self.educationDropdown.setObjectName("educationDropdown")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(100, 280, 80, 30))
        self.saveButton.setObjectName("saveButton")
        self.clearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(200, 280, 80, 30))
        self.clearButton.setObjectName("clearButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form Validation"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_email.setText(_translate("MainWindow", "Email:"))
        self.label_age.setText(_translate("MainWindow", "Age:"))
        self.label_phone.setText(_translate("MainWindow", "Phone Number:"))
        self.phoneInput.setInputMask(_translate("MainWindow", "+62 999 9999 9999"))
        self.label_address.setText(_translate("MainWindow", "Address:"))
        self.label_gender.setText(_translate("MainWindow", "Gender:"))
        self.label_education.setText(_translate("MainWindow", "Education:"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
